# app/utils/column_mapping.py

COLUMN_RENAME_MAP = {
    "Age (yrs)": "age_yrs",
    "Weight (Kg)": "weight_kg",
    "Height(Cm)": "heightcm",
    "BMI": "bmi",
    "Blood Group": "blood_group",
    "Pulse rate(bpm)": "pulse_ratebpm",
    "RR (breaths/min)": "rr_breaths/min",
    "Hb(g/dl)": "hbg/dl",
    "Cycle(R/I)": "cycler/i",
    "Cycle length(days)": "cycle_lengthdays",
    "Marraige Status (Yrs)": "marraige_status_yrs",
    "Pregnant(Y/N)": "pregnanty/n",
    "No. of aborptions": "no._of_aborptions",
    "I   beta-HCG(mIU/mL)": "i___beta-hcgmiu/ml",
    "II    beta-HCG(mIU/mL)": "ii____beta-hcgmiu/ml",
    "FSH(mIU/mL)": "fshmiu/ml",
    "LH(mIU/mL)": "lhmiu/ml",
    "FSH/LH": "fsh/lh",
    "Hip(inch)": "hipinch",
    "Waist(inch)": "waistinch",
    "Waist:Hip Ratio": "waist:hip_ratio",
    "TSH (mIU/L)": "tsh_miu/l",
    "AMH(ng/mL)": "amhng/ml",
    "PRL(ng/mL)": "prlng/ml",
    "Vit D3 (ng/mL)": "vit_d3_ng/ml",
    "PRG(ng/mL)": "prgng/ml",
    "RBS(mg/dl)": "rbsmg/dl",
    "Weight gain(Y/N)": "weight_gainy/n",
    "hair growth(Y/N)": "hair_growthy/n",
    "Skin darkening (Y/N)": "skin_darkening_y/n",
    "Hair loss(Y/N)": "hair_lossy/n",
    "Pimples(Y/N)": "pimplesy/n",
    "Fast food (Y/N)": "fast_food_y/n",
    "Reg.Exercise(Y/N)": "reg.exercisey/n",
    "BP _Systolic (mmHg)": "bp__systolic_mmhg",
    "BP _Diastolic (mmHg)": "bp__diastolic_mmhg",
    "Follicle No. (L)": "follicle_no._l",
    "Follicle No. (R)": "follicle_no._r",
    "Avg. F size (L) (mm)": "avg._f_size_l_mm",
    "Avg. F size (R) (mm)": "avg._f_size_r_mm",
    "Endometrium (mm)": "endometrium_mm",
}
